import type { FormStrings } from "../types/formTypes";
import { API_BASE_URL, background, WALLPAPER } from "./env";

export const newProductStrings: FormStrings = {
  title: "Publica un Nuevo Producto",
  imageUrl: `${API_BASE_URL}${WALLPAPER}${background.newProduct}`,
  inputs: [
    {
      label: "Categoría",
      placeholder: "Ej: Teclado",
      type: "select",
      id: "category",
      validation: "Debe seleccionar una opción",
      optional: false,
    },
    {
      label: "Nombre",
      placeholder: "Ej: Teclado Pro BT-250",
      type: "text",
      id: "product_name",
      validation: "Debe tener al menos 2 caracteres",
      optional: false,
    },
    {
      label: "Marca",
      placeholder: "Ej: Intel",
      type: "text",
      id: "brand",
      validation: "Debe tener al menos 2 caracteres",
      optional: false,
    },
    {
      label: "Modelo",
      placeholder: "Ej: Pro BT-250",
      type: "text",
      id: "model",
      validation: "Debe tener al menos 2 caracteres",
      optional: false,
    },
    {
      label: "Descripción",
      placeholder: "Ej: Teclado mecánico con luces RGB",
      type: "textarea",
      id: "description",
      validation: "Debe tener al menos 2 caracteres",
      optional: false,
    },
    {
      label: "Precio",
      placeholder: "Ej: $150",
      type: "number",
      min: 1,
      id: "price",
      validation: "Debe ser mayor a $1",
      optional: false,
    },
    {
      label: "Cantidad",
      placeholder: "Ej: 50",
      type: "number",
      id: "quantity",
      validation: "Debe ser mayor a 0",
      optional: false,
    },
    {
      label: "Procesador",
      placeholder: "Ej: Intel i7-12700k",
      type: "text",
      id: "cpu",
      validation: "Debe tener al menos 2 caracteres",
      optional: true,
    },
    {
      label: "GPU",
      placeholder: "Ej: Nvidia RTX 5090",
      type: "text",
      id: "gpu",
      validation: "Debe tener al menos 2 caracteres",
      optional: true,
    },
    {
      label: "RAM",
      placeholder: "Ej: Kingston Fury 32gb DDR5 6000MT/s",
      type: "number",
      id: "ram",
      validation: "Debe tener al menos 2 caracteres",
      optional: true,
    },
    {
      label: "Tipo de Almacenamiento",
      placeholder: "Ej: SSD",
      type: "text",
      id: "storage_type",
      validation: "Debe tener al menos 2 caracteres",
      optional: true,
    },
    {
      label: "Cantidad de almacenamiento",
      placeholder: "Ej: 480gb",
      type: "number",
      id: "storage",
      validation: "Debe ser mayor a 0",
      optional: true,
    },
    {
      label: "Batería",
      placeholder: "Ej: 5000MAh",
      type: "number",
      id: "battery",
      validation: "Debe ser mayor a 0",
      optional: true,
    },
    {
      label: "Tamaño de pantalla",
      placeholder: "Ej: 15.6",
      type: "number",
      id: "display_size",
      validation: "Debe ser mayor a 0",
      optional: true,
    },
    {
      label: "Resolución de pantalla",
      placeholder: "Ej: 1920x1080",
      type: "text",
      id: "display_resolution",
      validation: "Debe tener al menos 2 caracteres",
      optional: true,
    },
    {
      label: "Tipo de panel de pantalla",
      placeholder: "Ej: Fast IPS",
      type: "text",
      id: "panel_type",
      validation: "Debe tener al menos 2 caracteres",
      optional: true,
    },
    {
      label: "Suba fotos del Producto",
      uploadButtonLabel: "Subir fotos",
      placeholder: "Arrastra y suelta tus fotos aquí",
      type: "file",
      id: "image_url",
      validation: "Se requiere al menos un archivo",
      optional: false,
    },
  ],
  toastSuccess: {
    severity: "success",
    summary: "Publicación completa",
  },
  toastError: {
    severity: "error",
    summary: "Error al publicar",
  },
  primaryButton: "Publicar",
  secondaryButton: "Cancelar",
};
